import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { randomBytes } from "crypto";

const Home: NextPage = () => {
  const createEvent = api.events.createEvent.useMutation();
  const deleteEvent = api.events.deleteEvent.useMutation();
  // const createUser = api.users.createUser.useMutation();
  const updateEvent_addresss = api.events.updateEvent_addresss.useMutation();

  // const user = api.users.getUser.useQuery({
  //   email: "test@aer.com",
  // });
  // const events = api.events.getEventList.useQuery({
  //   email: "haiyuezhang63@gmail.com",
  // });
  // const event = api.events.getEvent.useQuery({
  //   eventId: "e02581e4-a096-4e79-9081-3dcc453087f6",
  // });
  //
  // console.log(user)



  // const createUser = api.users.createUser.useMutation();
  //
  // const allUsers = api.users.getAllUsers.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <h2 className="text-center text-white">
            <p className="bg-slate-500 text-3xl">
              U need to refrsh to see new users
            </p>
            {/*{allUsers.data?.map((user) => user.name).join(", ")}*/}
          </h2>
          <button
            className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
            onClick={() =>
              // createEvent.mutate({
              //   occuringDays: "2023-04-06",
              //   begins: '2023-04-06T12:30:00.000Z',
              //   ends: "2023-04-06T12:30:00.000Z",
              //   type: 'DAYSOFWEEK',
              //   email: 'haiyuezhang63@gmail.com',
              //   address: "unnion",
              // })
              // updateEvent_addresss.mutate({
              //   host_email: 'haiyuezhang63@gmail.com',
              //   address: 'qsqs',
              //   eventId: '568b0bed-63c6-4296-8e98-0c74e30f3394'
              // })
              deleteEvent.mutate({
                host_email: 'haiyuezhang63@gmail.com',
                eventId: '568b0bed-63c6-4296-8e98-0c74e30f3394'
              })
            }
          >
            <a>Create a randomized user</a>
          </button>
          {/*<h3 className="text-5xl text-white">{`This email belongs to ${*/}
          {/*  // user.data?.name ?? "no user found"*/}
          {/*  events.data?.id?? "no user found"*/}
          {/*}`}</h3>*/}
        </div>
      </main>
    </>
  );
};

export default Home;